### ISSUE TITLE
Agent state file is not persisted in certain circumstances

### ISSUE THREAD

**Issue by binarylogic** [timberio/agent#140]
Related https://github.com/timberio/agent/issues/8

We had a client report that the state file is not being persisted properly on their machine resulting in the agent thinking the file has been rotated and sending data from the beginning. Specifically these are nginx logs. The logs being tailed are:

1. `/var/log/nginx/access.log`
2. `/var/log/nginx/error.log`

The state files are persisted in the same directory with the names:

1. `/var/log/nginx/access.log-state.json`
2. `/var/log/nginx/error.log-state.json`

My gut tells me that the file naming might be causing it to get cleaned up or rotated in some way. We should re-think the best way to persist state files:

1. Is putting the state file in the same directory the best option? Is there a better place to persist state?
2. I dislike using `.log` in the name. Ideally we would strip extensions so that the name would be `error-timber-agent-state.json` (or something similar).

**Comment by DavidAntaramian** [comment]
@binarylogic I believe this should just be closed in favor of #8 which documents possible solutions, because that issue already answers both your questions:

1. No it is not the best option to put the state file in the same directory. Linux and BSD systems already have defined locations to place these types of files as documented in #8.

2. This is also addressed in #8 where I suggest that the state file first be moved to the appropriate state directory and then either be maintained as a single file for the agent with the state of every tracked file listed therein or otherwise that every file should be given its own state file under the state management directory with a hash of the full path as the name of the state file.

**Comment by binarylogic** [comment]
Sounds good
