### ISSUE TITLE
Retry specific Timber API response codes

### ISSUE THREAD

**Issue by binarylogic** [timberio/agent#30]
`429`, `500`, `502`, `503`, and `504` should be retried, indefinitely, with an exponential back-off (with [jitter](https://www.awsarchitectureblog.com/2015/03/backoff.html)). The back-off should be capped at 30 seconds. Our agents should never stop attempting delivery, this ensures that we can recover during an outage.

**Comment by DavidAntaramian** [comment]
@binarylogic We use [go-retryablehttp](https://github.com/hashicorp/go-retryablehttp) for this effect already. It will automatically retry, though it doesn't use the exact algorithm you've specified.

**Comment by binarylogic** [comment]
Sounds good. I assume after the retries fail the buffer will not get flushed? The agent will indefinitely retry the same lines until they succeed and the state file checkpoint will not advance.

**Comment by DavidAntaramian** [comment]
@binarylogic If all the retries fail, the system dismisses the buffer and moves on. This is sound practice, in my opinion. The agent has no guarantee about when the remote service will become available again.

There's a further issue with data over stdin, since the upstream service (such as syslog) will want to keep sending data forward. There's no way to signal upstream to stop data flow until the service becomes available again.
