### ISSUE TITLE
Internal logging should be routed through our own log.go

### ISSUE THREAD

**Issue by binarylogic** [timberio/agent#31]
Because logging can be configured, we should create a `log.go` module that provides a logger based on that configuration. All files should rely on this for logging. Ideally the functions provided would take a typed list of arguments to accomplish structured logging. Ex:

```go
logger, _ := zap.NewProduction()
defer logger.Sync()
logger.Info("failed to fetch URL",
  // Structured context as strongly typed Field values.
  zap.String("url", url),
  zap.Int("attempt", 3),
  zap.Duration("backoff", time.Second),
)
```

**Comment by mikemorris** [comment]
We have a Heroku app using the Timber Elixir client and the log drain integration, and noticed that messages that don't pass through the Elixir client do end up in Timber logs, but aren't categorized by level correctly.

As an example, we have a small shell script wrapper around this app for messages like the following, which always end up as `INFO` instead of conforming to [syslog standards](https://en.wikipedia.org/wiki/Syslog#Severity_level). The `[LEVEL]` prefix does get removed from the message though.
```
echo "[crit] App crashed"
echo "[notice] Logging erl_crash.dump"
```
Is this the appropriate issue for tracking this enhancement?

**Comment by binarylogic** [comment]
@mikemorris so sorry I did not see this when it was filed. I've opened an internal issue for this as it's a parsing issue.

I'm closing this issue since the original issue is no longer relevant to the agent.
